import { Footer } from '@/components/Footer/Footer';
import { AppBar, Button, Container, Toolbar, Typography } from '@mui/material';
import type { Metadata } from 'next'
// import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import  ThemRegistry from "@/providers/ThemeRegistry"
import Link from 'next/link';
import { ReactNode } from "react"

// const inter = Roboto({ subsets: ['latin'] })

const HEADER_SX = {
  flexGrow: 1,
}
export const metadata: Metadata = {
  title: 'Homework_06',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemRegistry options={{ key: 'mui'}}>
          <div className='layout'>
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={HEADER_SX}>
                React-Router + Material-UI
              </Typography>
              <Button component={Link} href="/" color="inherit">
                Photos
              </Button>
              <Button component={Link} href="/posts" color="inherit">
                Posts
              </Button>
              <Button component={Link} href="/comments/1" color="inherit">
                Comments
              </Button>
              <Button component={Link} href="/users" color="inherit">
                Users
              </Button>
            </Toolbar>
          </AppBar>
          <main className='main'>
            <Container>
            {children}
            </Container>
          </main>
          <Footer />
          </div>
        </ThemRegistry>
        </body>
    </html>
  )
}
